steps:
  # 1. Build da imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '-t',
      'us-central1-docker.pkg.dev/bordados-e-charme/cloud-run-source-deploy/bordados-e-charme/atualizacao-de-pedidos-build:$COMMIT_SHA',
      '.'
    ]

  # 2. Tag latest
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'tag',
      'us-central1-docker.pkg.dev/bordados-e-charme/cloud-run-source-deploy/bordados-e-charme/atualizacao-de-pedidos-build:$COMMIT_SHA',
      'us-central1-docker.pkg.dev/bordados-e-charme/cloud-run-source-deploy/bordados-e-charme/atualizacao-de-pedidos-build:latest'
    ]

  # 3. Push da imagem pro Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/bordados-e-charme/cloud-run-source-deploy/bordados-e-charme/atualizacao-de-pedidos-build:$COMMIT_SHA'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/bordados-e-charme/cloud-run-source-deploy/bordados-e-charme/atualizacao-de-pedidos-build:latest'
    ]

  # 4. Deploy no Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'jobs', 'deploy', 'atualizacao-de-pedidos-job',
        '--image=us-central1-docker.pkg.dev/bordados-e-charme/cloud-run-source-deploy/bordados-e-charme/atualizacao-de-pedidos-build:latest',
        '--region=us-central1',
        '--platform=managed',
        '--allow-unauthenticated'
      ]

images:
  - 'us-central1-docker.pkg.dev/bordados-e-charme/cloud-run-source-deploy/bordados-e-charme/atualizacao-de-pedidos-build:$COMMIT_SHA'
  - 'us-central1-docker.pkg.dev/bordados-e-charme/cloud-run-source-deploy/bordados-e-charme/atualizacao-de-pedidos-build:latest'
